In [9]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

url = 'http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=MGUyYzQxYzMxMTRiN2EzYzYwOGY5MGJhODViMjA1OWQ=&format=json&jsonVD=Y&userStatsId=kj004419/101/DT_1B040A3/2/1/20200214142601&prdSe=M&newEstPrdCnt=1'

response = requests.get(url)
response

json = response.json()

df = json_normalize(json)
df.head()

,TBL_NM,PRD_DE,TBL_ID,ITM_NM,ITM_NM_ENG,ITM_ID,UNIT_NM,ORG_ID,UNIT_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,DT,PRD_SE,C1,C1_NM,C1_NM_ENG
0,행정구역(시군구)별 성별 인구수,202001,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51847509,M,00,전국,Whole country
1,행정구역(시군구)별 성별 인구수,202001,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,9733509,M,11,서울특별시,Seoul
2,행정구역(시군구)별 성별 인구수,202001,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,3411819,M,26,부산광역시,Busan
3,행정구역(시군구)별 성별 인구수,202001,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2436488,M,27,대구광역시,Daegu
4,행정구역(시군구)별 성별 인구수,202001,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2956119,M,28,인천광역시,Incheon